In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
print(torch.__version__)

2.5.0+cu121


## Introduction to tensors

#### Scalar

In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as python int
scalar.item()

7

#### vector

In [6]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

#### Matrix

In [9]:
matrix=torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([1, 2])

In [12]:
matrix.shape

torch.Size([2, 2])

#### Tensor

In [13]:
tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
tensor1=torch.tensor([[[1,2,3],
               [4,3,5],
               [7,8,9]]])

In [18]:
tensor1[0][0][1]

tensor(2)

## Random Tensors

In [19]:
# Create a random tensor of size (3,4)
random_numbers=torch.rand(size=(3,4))
# random_numbers=torch.rand(3,4)    ------- alternative
random_numbers

tensor([[0.3263, 0.5907, 0.4142, 0.1666],
        [0.7741, 0.2555, 0.7292, 0.5174],
        [0.8869, 0.4893, 0.2930, 0.8991]])

In [20]:
random_numbers.ndim

2

In [21]:
random_num=torch.rand(1,3,4)
random_num

tensor([[[0.1874, 0.1201, 0.8769, 0.8250],
         [0.7625, 0.4535, 0.3684, 0.3703],
         [0.1544, 0.0312, 0.0768, 0.8211]]])

In [22]:
random_num.ndim

3

In [23]:
random_tensor=torch.rand(5,6)
random_tensor

tensor([[0.7866, 0.7114, 0.0589, 0.5186, 0.3511, 0.4874],
        [0.6789, 0.7182, 0.1492, 0.2925, 0.6887, 0.3730],
        [0.1120, 0.7893, 0.3437, 0.3320, 0.9435, 0.2762],
        [0.3424, 0.3040, 0.5014, 0.3246, 0.7022, 0.5354],
        [0.8356, 0.7962, 0.0695, 0.9908, 0.0534, 0.8124]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor.shape

torch.Size([5, 6])

## Creating a random tensor with similar to an image

In [26]:
random_image_tensor=torch.rand(size=(3,224,224))  # Height,width,color channels(red,green,blue)
random_image_tensor

tensor([[[0.1857, 0.6282, 0.1348,  ..., 0.7242, 0.5401, 0.6832],
         [0.5603, 0.4825, 0.6250,  ..., 0.9016, 0.4641, 0.5593],
         [0.2994, 0.0814, 0.1278,  ..., 0.6921, 0.3573, 0.8579],
         ...,
         [0.0235, 0.6152, 0.6106,  ..., 0.4308, 0.4646, 0.2562],
         [0.7681, 0.2474, 0.7364,  ..., 0.1781, 0.1615, 0.1878],
         [0.8172, 0.6146, 0.5874,  ..., 0.3801, 0.4018, 0.2169]],

        [[0.4042, 0.2600, 0.5491,  ..., 0.2270, 0.6679, 0.4779],
         [0.0250, 0.2545, 0.1763,  ..., 0.5315, 0.0293, 0.0236],
         [0.4400, 0.5516, 0.1509,  ..., 0.0443, 0.5044, 0.3194],
         ...,
         [0.7688, 0.0512, 0.2622,  ..., 0.4259, 0.0935, 0.5048],
         [0.3708, 0.6846, 0.2015,  ..., 0.7929, 0.0948, 0.6292],
         [0.5018, 0.2299, 0.8175,  ..., 0.1426, 0.3759, 0.0237]],

        [[0.9555, 0.4859, 0.0693,  ..., 0.9565, 0.7227, 0.9108],
         [0.6365, 0.8734, 0.7129,  ..., 0.9724, 0.2929, 0.2466],
         [0.2136, 0.5254, 0.8391,  ..., 0.3090, 0.7649, 0.

In [27]:
random_image_tensor.shape

torch.Size([3, 224, 224])

In [28]:
random_image_tensor.ndim

3

### Zero tensors

In [29]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zeros*random_numbers

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
sample=torch.zeros(size=(5,4))
print(sample)
print(sample.shape)
print(sample.ndim)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([5, 4])
2


### Ones tensors

In [32]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones*random_numbers

tensor([[0.3263, 0.5907, 0.4142, 0.1666],
        [0.7741, 0.2555, 0.7292, 0.5174],
        [0.8869, 0.4893, 0.2930, 0.8991]])

In [34]:
ones.dtype

torch.float32

In [35]:
zeros.dtype

torch.float32

In [36]:
sample=torch.ones(size=(5,4))
print(sample)
print(sample.ndim)
print(sample.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2
torch.Size([5, 4])


## Creating a range of tensors and tensors like

In [37]:
one_to_ten=torch.arange(0,10,1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating tensor like

In [38]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
random_numbers

tensor([[0.3263, 0.5907, 0.4142, 0.1666],
        [0.7741, 0.2555, 0.7292, 0.5174],
        [0.8869, 0.4893, 0.2930, 0.8991]])

In [40]:
zero_random_numbers=torch.zeros_like(input=random_numbers)
zero_random_numbers

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating ones like

In [41]:
ones_random_numbers=torch.ones_like(input=random_numbers)
ones_random_numbers

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating rand like

In [42]:
random_random_like=torch.rand_like(input=ones_random_numbers)
random_random_like

tensor([[0.9849, 0.7372, 0.4847, 0.9659],
        [0.1903, 0.9158, 0.5348, 0.0760],
        [0.8611, 0.8779, 0.4487, 0.2931]])

## Tensor Data type

In [43]:
# Float 32 tensor

float_32_dtype=torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_dtype

tensor([3., 6., 9.])

In [44]:
float_32_dtype.dtype

torch.float32

In [45]:
# Float 16 tensor

float_16_dtype=torch.tensor([3.0,6.0,9.0],
                            dtype=torch.float16,   # Data type of the tensors
                            device=None,           # what device is your tensor on
                            requires_grad=False)   # whether to track or not to track gradient with tensor operation
print(float_16_dtype)
print(float_16_dtype.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


## Converting float 32 to float 16

In [46]:
float_16_dtype=float_32_dtype.type(torch.float16)
float_16_dtype

tensor([3., 6., 9.], dtype=torch.float16)

In [47]:
float_16_dtype.dtype

torch.float16

In [48]:
float_32_dtype*float_16_dtype

tensor([ 9., 36., 81.])

#### Creating tensors with int

In [49]:
int_tensors=torch.tensor([1,2,3,4],dtype=torch.int16)
int_tensors

tensor([1, 2, 3, 4], dtype=torch.int16)

### Converting float-32 to int-16

In [50]:
converted_int_32=float_32_dtype.type(torch.int16)

In [51]:
converted_int_32

tensor([3, 6, 9], dtype=torch.int16)

In [52]:
int_32_dtype=torch.tensor([1,2,3],dtype=torch.int32)
int_32_dtype

tensor([1, 2, 3], dtype=torch.int32)

### Multiplying float 32 and int 32

In [53]:
float_32_dtype*int_32_dtype

tensor([ 3., 12., 27.])

# Getting information from tensors

In [54]:
sample_tensor=torch.rand(size=(3,4))
sample_tensor

tensor([[0.7627, 0.1484, 0.6078, 0.7647],
        [0.0610, 0.0212, 0.9221, 0.7703],
        [0.8511, 0.6170, 0.0463, 0.2862]])

In [55]:
print(f"datatype : {sample_tensor.dtype}")
print(f"shape : {sample_tensor.shape}")
print(f"device :  {sample_tensor.device}")


datatype : torch.float32
shape : torch.Size([3, 4])
device :  cpu


In [56]:
sample_tensor=sample_tensor.type(torch.float16)

In [57]:
print(f"datatype : {sample_tensor.dtype}")
print(f"shape : {sample_tensor.shape}")
print(f"device :  {sample_tensor.device}")

datatype : torch.float16
shape : torch.Size([3, 4])
device :  cpu


### Manipulating tensors
Addition

Subtraction

Multiplication

Division

Matrix multiplication


In [58]:
# create a tensor

tensor=torch.tensor([1,2,3])

In [59]:
# Adding 10 to tensor

tensor+10

tensor([11, 12, 13])

In [60]:
# Subtracting 10 from tensor

tensor-10

tensor([-9, -8, -7])

In [61]:
# Multiplying 10 to tensor

tensor*10

tensor([10, 20, 30])

In [62]:
# Try in-built functions

torch.mul(tensor,10)

tensor([10, 20, 30])

In [63]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [64]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Matrix multiplication

#### Two Ways to perform
 1.Element wise multiplication

 2.Matrix multiplication

In [65]:
# Element wise multiplication

print(f"{tensor} * {tensor}")
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [66]:
# Matrix multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [67]:
m=torch.tensor([[[2,3,4],[5,6,7],[8,9,8]]])
n=torch.tensor([[[4,5,6],[6,5,9],[1,2,3]]])
ans=torch.matmul(m,n)

ans

tensor([[[ 30,  33,  51],
         [ 63,  69, 105],
         [ 94, 101, 153]]])

In [68]:
ans.ndim

3

In [69]:
# matrix multiplication

%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 963 µs, sys: 1.08 ms, total: 2.04 ms
Wall time: 3.1 ms


In [70]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 454 µs, sys: 798 µs, total: 1.25 ms
Wall time: 1.45 ms


tensor(14)

### Matrix multiplication --- Two rules

##### 1.Inner dimension must match
##### 2.Result matrix has shape of outer dimension

In [71]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[1.6243, 0.6597, 1.4406],
        [1.3489, 0.6091, 1.1907],
        [1.0898, 0.9318, 0.6189]])

In [72]:
torch.matmul(torch.rand(3,4),torch.rand(4,2))

tensor([[1.1829, 1.5088],
        [0.7751, 1.9749],
        [1.2697, 1.4731]])

In [73]:
torch.matmul(torch.rand(5,2),torch.rand(2,5))

tensor([[0.4287, 0.7861, 0.4334, 0.4903, 0.6140],
        [0.6539, 1.3413, 0.7768, 0.8282, 0.9934],
        [0.4027, 0.6145, 0.3062, 0.3905, 0.5272],
        [0.5636, 0.8940, 0.4563, 0.5658, 0.7513],
        [0.3406, 0.8608, 0.5366, 0.5230, 0.5823]])

# One of the most common errors in deep learning : Shape error

In [74]:
# shape for matrix multiplication

tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_b=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

# torch.mm(tensor_A,tensor_b)

## To fix shape issues we transpose the matrix

In [75]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [76]:
tensor_b

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [77]:
tensor_b.T.shape , tensor_b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [78]:
torch.mm(tensor_A,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [79]:
torch.mm(tensor_A,tensor_b.T).shape

torch.Size([3, 3])

### Tensor Aggregation
###  Finding the Min, Max, Sum, Mean, etc

In [80]:
# create a tensor

x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
# Finding minimum

torch.min(x), x.min()

(tensor(0), tensor(0))

In [82]:
# Finding max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [83]:
x.dtype

torch.int64

In [84]:
# Finding the mean

torch.mean(x.type(torch.float32))

tensor(45.)

##### Mean in torch requires floats of data type

In [85]:
x.type(torch.float32).mean()

tensor(45.)

In [86]:
# Finding sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [87]:
# FInding the index of the min, max

x.argmin()   # returns the index number

tensor(0)

In [88]:
x.argmax()   # returns the index value

tensor(9)

### Reshaping, Stacking, Squeezing, and unsqueezing tensors

In [89]:
x=torch.arange(1.0,11)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [90]:
# Adding an extra dimension

x_reshaped=x.reshape(1,10)
x_reshaped,x_reshaped.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [91]:
x_reshaped=x.reshape(10,1)
x_reshaped,x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [92]:
x_reshaped=x.reshape(5,2)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [93]:
x_reshaped=x.reshape(2,5)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [94]:
# Change the view
z=x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [95]:
# Change the view
z=x.view(5,2)
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [96]:
# Changing the z changes x (because a view of a tencosr shares the same memory as the original memory)

z[:,0]=5

z,x


(tensor([[ 5.,  2.],
         [ 5.,  4.],
         [ 5.,  6.],
         [ 5.,  8.],
         [ 5., 10.]]),
 tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]))

In [97]:
# Stack tensors on top of each other

x_stack=torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])

In [98]:
x_stack=torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 5.,  5.,  5.,  5.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  8.,  8.,  8.],
        [ 5.,  5.,  5.,  5.],
        [10., 10., 10., 10.]])

In [99]:
x_stack=torch.stack([x,x,x,x],dim=-1)
x_stack

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 5.,  5.,  5.,  5.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  8.,  8.,  8.],
        [ 5.,  5.,  5.,  5.],
        [10., 10., 10., 10.]])

In [100]:
x_stack=torch.stack([x,x,x,x],dim=-2)
x_stack

tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])

### Squeeze and unsqueeze

In [101]:
x=x.reshape(1,10)
x,x.shape

(tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]]),
 torch.Size([1, 10]))

In [102]:
x_squeezed=torch.squeeze(x,dim=0)
x_squeezed,x_squeezed.shape

(tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]), torch.Size([10]))

In [103]:
print(f"Previous tensor : {x}")
print(f"Previous shape : {x.shape}")

print(f"Previous tensor : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

Previous tensor : tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])
Previous shape : torch.Size([1, 10])
Previous tensor : tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.])
Previous shape : torch.Size([10])


In [104]:
x_unsqueezed=torch.unsqueeze(x_squeezed,dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]]),
 torch.Size([1, 10]))

In [105]:
print(f"Previous tensor : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

print(f"Previous tensor : {x_unsqueezed}")
print(f"Previous shape : {x_unsqueezed.shape}")

Previous tensor : tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.])
Previous shape : torch.Size([10])
Previous tensor : tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])
Previous shape : torch.Size([1, 10])


### Permute-- re arranges the dimensions of a target tensor in specified order

In [106]:
x_original=torch.rand(size=(224,224,3))


# Permute the original tensor to rearrange the axis or dim order

x_permuted=torch.permute(x_original,(2,0,1))  # index

# axis 0->1, 1->2, 2->0


print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [107]:
x_original[0][0][0]=72345
x_original[0][0][0], x_permuted[0][0][0]

(tensor(72345.), tensor(72345.))

#### Indexing

In [108]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [109]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [110]:
x[0][0]

tensor([1, 2, 3])

In [111]:
x[0][0][1]

x[0][1][1]

tensor(5)

In [112]:
x[0][2][2]

tensor(9)

In [113]:
x[:,:,1]

tensor([[2, 5, 8]])

In [114]:
x[:,:,2]

tensor([[3, 6, 9]])

In [115]:
x[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [116]:
x[:,1,1]

tensor([5])

In [117]:
x[0,0,:]

tensor([1, 2, 3])

In [118]:
# index to return 9

x[:,2,2]

tensor([9])

In [119]:
x[:,:,2]

tensor([[3, 6, 9]])

#### Pytorch and Numpy

torch.from_numpy(ndarray) --> from numpy to tensors

torch.tensor.numpy()

In [120]:
# Numpy array to tensor
import numpy as np

array=np.arange(1.0,8.0)

tensor= torch.from_numpy(array)

array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

#### When converting th numpy into tensor the default float 64 remains same

In [121]:
tensor.dtype

torch.float64

In [122]:
array.dtype

dtype('float64')

In [123]:
tensor=tensor.type(torch.float32)

In [124]:
tensor.dtype

torch.float32

In [125]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [126]:
array=np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
tensor=torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

### What happens when we add 1 to array does it reflect on tensor

In [128]:
array=array+1
array, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [129]:
numpy=np.arange(1,10)
tensors=torch.from_numpy(numpy)
tensors

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Converting numpy to tensors

In [130]:
tensors=torch.ones(7)
numpy=tensors.numpy()
tensors, numpy

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [131]:
numpy.dtype

dtype('float32')

### What happens when we add 1 to tensors does it reflect on array

In [132]:
tensors=tensors+1
tensors, numpy

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (Trying to take random out of random)

#### How neural network learns :

`Start with random numbers -> tensor operation -> update random numbers to try and make them better representations of the data -> agaiin ->again -> again... `

#### To reduce the randomness in pytorch and numpy a concept called ***random seed***

random seed is used to flavour the randomness

In [133]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A==random_tensor_B)

tensor([[0.0431, 0.1137, 0.4832, 0.2200],
        [0.8381, 0.1320, 0.5032, 0.6394],
        [0.3723, 0.7393, 0.5012, 0.7048]])
tensor([[0.1368, 0.0089, 0.9129, 0.2593],
        [0.1995, 0.8218, 0.3899, 0.7821],
        [0.2637, 0.9923, 0.6308, 0.8383]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [135]:
# Making use of random_seed

random_seed=42

torch.manual_seed(random_seed)

random_tensor_c=torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_d=torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)

print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Accessing GPU's

#### GPU makes the numerical computation faster

In [1]:
import torch
torch.cuda.is_available()

True

In [9]:
# setting the device to cuda

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


device

device(type='cuda')

In [3]:
torch.cuda.device_count()

1

### Agnostic code

### Putting tensors on GPU

In [20]:
tensor=torch.tensor([1,2,3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

###### cuda is 0 because of index which says 1 gpu

In [28]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving back to CPU since the numpy supports on cpu

if tensor is on gpu can't transfer it to numpy

In [32]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [33]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')